### ISSUE TITLE
Lab2 peer review

### ISSUE THREAD

**Issue by amadrezafrh** [S309100/CI2324#3]
Dear Samaneh,

I have reviewed your Lab2 codes and I have few suggestions for you.

For the rule-based strategy, you can add an algorithm that selects minimum state nim_sum instad of passing pure_random. For the main algorithm, I believe you can modify it as below: 
```python
    # Find a move that changes the current nim-sum to zero
    for r, num_objects in enumerate(state.rows):
        for remove in range(1, min(state._k, num_objects) + 1 if state._k else num_objects + 1):
            # Create a copy of the state and perform the move
            if nim_sum(state) != 0:
                return Nimply(r, remove)
    # If no such move is found, fall back to a random move
    return min_algorithm(state)
```
Where min_algorithm(state) is the one I mentioned before. Furthermore, in the EA algorithm you have done a great algorithm. For evaluations you can increase (or add) some number of epochs and calculate the average wins. Moreover, you can add another term for the fitness calls which considers both possibilities of starting the game for your strategies. The main reason for considering this method for your fitness calls is the inconsistency of winning rate when you change the first player (at least for me).  Thanks for reading my review.

Good luck,
Ahmadreza

**Comment by SamiSani68** [comment]
Dear Ahmadreza,

Thank you for your thorough review of my Lab2 code and for the constructive suggestions on how to enhance the rule-based strategy and the evolutionary algorithm within my Nim game implementation.

Regarding the rule-based strategy, I appreciate your idea of adding an algorithm to select the move that results in the minimum nim-sum instead of relying on pure_random. This approach seems to align with the goal of making more strategic moves that could potentially lead to a higher win rate.

For the evolutionary algorithm, I find your recommendations insightful. Increasing the number of epochs and calculating the average wins over those epochs should indeed provide a more robust evaluation of the strategy's performance. Additionally, considering both possibilities of who starts the game in the fitness evaluation is a valuable suggestion that should help in creating a more balanced and fair assessment of the strategy's effectiveness.

I will work on implementing these enhancements to the code. Your input is instrumental in refining the strategies and will surely contribute to a more sophisticated game agent.

Once again, thank you for your time and assistance.

Best regards,
Samaneh
